version: '3'
services:

  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=oeh8eelaal0xahj0Hiem
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - ./registries.yaml:/etc/rancher/k3s/registries.yaml
    - ./manifests:/src/manifests
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443
    links:
      - registry:local-registry.shaka.xyz

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=oeh8eelaal0xahj0Hiem
    links:
      - registry:local-registry.shaka.xyz
    volumes:
    - ./registries.yaml:/etc/rancher/k3s/registries.yaml

  registry:
    image: registry

  builder:
    image: docker:dind
    privileged: true
    links:
      - registry:local-registry.shaka.xyz
    volumes:
      - "./:/src/"
    command:
      - "--insecure-registry"
      - "local-registry.shaka.xyz:5000"

volumes:
  k3s-server: {}
